#' A function to aggregate age comps generated by a n.area OM into a single area for a single area EM (maybe someday add the code to 
#' make into a more flexible combination, like 3 or 4 areas instead of 1)
#' 
#' @param comp - the age comps by area (n.areas) to aggregate into a single age comp vector to add to the .dat file
#' @param num.areas - the number of areas in the OM
#' @param weights - the 
#' @param 
#'
#' @return Vector proportional age comps combined over n.area and weighted by catch 


aggr_agecomp <- function(input.comps, num.areas, harvest.num) {

  sum sampled age comps (in numbers) across sexes for each area
  sum harvest in number across sexes for each area
  weight comps by harvest in each area
  sum comps for each age across areas
  calculate proportions at age for the single area
  output and close function
  
temp.comp<-input.comps[y,,m,i]
  
report()
}
