#' A function to aggregate age comps generated by a n.area OM into a single area for a single area EM (maybe someday add the code to 
#' make into a more flexible combination, like 3 or 4 areas instead of 1)
#' 
#' @param input.comps - the age comps by area (n.areas) to aggregate into a single age comp vector to add to the .dat file (input is a single year and sim of data)
#' @param num.areas - the number of areas in the OM
#' @param harvest.num - the catch in numbers by area (for weighting) for ages, for a single year and sim and fishery
#' @param 
#'
#' @return Vector proportional age comps combined over n.area and weighted by catch for a single year & sim and gear


aggr_agecomp <- function(input.comps, num.areas, harvest.num) {

  #sum sampled age comps (in numbers) across sexes for each area
  input.comps2 <- matrix(data=NA, nrow=num.areas, ncol=n.age, dimnames=list(areas,ages)) #=c(n.age, n.area), dimnames=list(years,ages,areas,sims))
  input.comps2[,] <- input.comps[1,,] + input.comps[2,,]
  #add zeros if needed
  input.comps2[is.na(input.comps2)] <- 0

  #sum harvest in number across sexes for each area
  sum.harvest <- matrix(data=NA, nrow=num.areas, ncol=n.age, dimnames=list(areas,ages))
  sum.harvest[,] <- harvest.num[1,,] + harvest.num[2,,]
  
  #calculate catch/harvest proportions by area for each age
  harvest.prop <- matrix(data=NA, nrow=num.areas, ncol=n.age, dimnames=list(areas,ages))
  a <- 1
  for(a in 1:n.age) {
    harvest.prop[,a] <- prop.table(sum.harvest[,a])  #for each age a, there's a n.areas (long) column of proportions by area
  }
  
  #for each age, weight comps by proportion of harvest in each area
  wt.comps <- matrix(data=NA, nrow=num.areas, ncol=n.age, dimnames=list(areas,ages))
  sum.comps <- as.vector(NA)  
  a <- 1
  for(a in 1:n.age) {
  wt.comps[,a] <-input.comps2[,a] * harvest.prop[,a]
  #sum comps for each age across areas, now have a vector of length=n.ages, weighted by area
  sum.comps[a] <- sum(wt.comps[,a])
  }
  
  #calculate proportions at age for the single area
  comp.prop <- as.vector(NA)
  comp.prop <- prop.table(sum.comps)
  
  #output and close function
  report(temp.comp)
}



#for testing
#input.comps <- array(dim=c(n.sex, n.age, n.area), dimnames=list(sexes,ages,areas))
#input.comps[,,] <- c(seq(from=1, to=360,by=1))
#num.areas=6

#harvest.num <- array(dim=c(n.sex, n.age, n.area), dimnames=list(sexes, ages, areas))  #Harvest (number) by gear type
#harvest.num[,,] <- c(seq(from=1, to=360, by=1))


