#' A function to aggregate age comps generated by a n.area OM into a single area, single sex, for a single area EM 
#' (maybe someday add the code to make into a more flexible combination, like 3 or 4 areas instead of 1)
#' 
#' @param input.comps - input is OM-generated age comps (dimensions: sex,age,area) representing a single year, gear, and sim 
#' @param harvest.num - the OM-generated catch in numbers by area (for weighting) for ages (dimensions: sex,age,area) representing a single year, gear, and sim 
#' @param 
#'
#' @return Vector proportional age comps combined over n.area and weighted by catch for a single year & sim and gear


aggr_agecomp <- function(input.comps, harvest.num, ACtype) { #ACtype 1 is fishery FOR CONDITIONING PERIOD, ACtype 2 is survey and fishery for forward projecting period

  #sum sampled age comps (in numbers) across sexes for each area
  input.comps2 <- matrix(data=NA, nrow=n.area, ncol=n.age, dimnames=list(areas,ages)) #=c(n.age, n.area), dimnames=list(years,ages,areas,sims))
  for (m in 1:n.area) {
    for (a in 1:n.age) {
  input.comps2[m,a] <- sum(input.comps[,a,m]) }}
  
  #add zeros if needed
  input.comps2[is.na(input.comps2)] <- 0

  #sum harvest/survey in number across sexes for each area
  if (ACtype==1){
    sum.harvest <- matrix(data=NA, nrow=n.area, ncol=n.age, dimnames=list(areas,ages))
    for (m in 1:n.area) {
    for (a in 1:n.age) {
    sum.harvest[m,a] <- sum(harvest.num[m,,a]) }}
  }  
  if (ACtype==2){
    sum.harvest <- matrix(data=NA, nrow=n.area, ncol=n.age, dimnames=list(areas,ages))
    for (m in 1:n.area) {
    for (a in 1:n.age) {
    sum.harvest[m,a] <- sum(harvest.num[,a,m]) }} 
  }  
  #calculate catch/harvest proportions by area for each age
  harvest.prop <- matrix(data=NA, nrow=n.area, ncol=n.age, dimnames=list(areas,ages))
  a <- 1
  for(a in 1:n.age) {
    harvest.prop[,a] <- prop.table(sum.harvest[,a])  #for each age a, there's a n.areas (long) column of proportions by area
  }
  
  #for each age, weight comps by proportion of harvest in each area
  wt.comps <- matrix(data=NA, nrow=n.area, ncol=n.age, dimnames=list(areas,ages))
  sum.comps <- as.vector(NA)  
  a <- 1
  for(a in 1:n.age) {
  wt.comps[,a] <-input.comps2[,a] * harvest.prop[,a]
  #sum comps for each age across areas, now have a vector of length=n.ages, weighted by area
  sum.comps[a] <- sum(wt.comps[,a])
  }
  
  #calculate proportions at age for the single area
  comp.prop <- as.vector(NA)
  comp.prop <- round(prop.table(sum.comps),4)
  
  #output and close function
  return(comp.prop)
}



#for testing
#input.comps <- array(dim=c(n.sex, n.age, n.area), dimnames=list(sexes,ages,areas))
#harvest.num <- array(dim=c(n.sex, n.age, n.area), dimnames=list(sexes, ages, areas))  #Harvest (number) by gear type

#    for(m in 1:n.area){
#    for(a in 1:n.age){ 
#    for(h in 1:n.sex){  
#      input.comps[h,a,m] <- Surv.AC[h,42,a,m,1]
#      harvest.num[h,a,m] <- Surv.RPN[h,42,a,m,1]
#    }
#  }
#}
#num.areas=6

#plot(Surv.AC[1,42,,2,1]~ages,typ="l",ylim=c(0,1.5))
#lines(input.comps[1,,2]~ages,typ="p")
#lines(input.comps2[2,]~ages,typ="p",col="red")
